### ISSUE TITLE
dasdutil.c: capacity_calc possible bug (not enforcing track record limits)

### ISSUE THREAD

**Issue by mstram** [rbowler/spinhawk#28]
Hi Roger,
I'm probably in the tiny minority (besides Tommy Sprinkle) of Hercules users', who does a lot of "No. O.S." / "bare metal testing / exploring / learning".

E.g. for a KL=0, DL=74 I'm getting  :
# Device     KeyLen  DataLen(dec)  Records Written     Expected (allowed) Number of Records
# --------    ------  -------     ---------------     ------------------------------------
#3330         0      74              161
#3340         0      74              105                             ??
#3350         0      74              236                             74
#3375         0      74              255                             74
#3380         0      74              255                             74
#3390-1       0      74              255                             ???
#3390-3       0      74              255                             ???
#3390-9       0      74              255                             ???
#9345         0      74              255                             ???

https://github.com/mstram/hercules-bare-metal-DASD-tests

https://github.com/mstram/hercules-bare-metal-DASD-tests/blob/master/test-results.txt

**Comment by rbowler** [comment]
Yes, this sounds plausible, Hercules doesn't have interblock gaps, so it can allow more records to be written on a track than a real DASD does. This will only be apparent at small block sizes. You could consider this as either a bug or a feature. At this stage in the game, I don't want to risk disruption to a stable product, so I am going to consider it as a feature.
