### ISSUE TITLE
Cross compilation not possible

### ISSUE THREAD

**Issue by blackpit73** [rbowler/spinhawk#30]
Currently, cross compiling is not possible.
Usually, autoconf projects can be cross compiled by giving the configure option --target=....,
but this does not work with spinhawk code, as the configure tries to execute temporary compiles, which is not possible with cross compiles.
It seems that the autoconf files needs update.

Concrete:
- use AC_CANONICAL_SYSTEM instead of AC_CANONICAL_HOST in configure.ac
  (AC_CANONICAL_SYSTEM calls AC_CANONICAL_HOST internally).
  This will solve most of the issues.
- check the usage of host_os/host_cpu/host_vendor, as most probabely in reality target_os/target_cpu/target_vendor should be used

**Comment by vapier** [comment]
there seems to be some confusion here as to how autotools works.

the `--target` option is *not* for cross-compiling packages.  using `--host` is correct.  hercules should not be using `AC_CANONICAL_SYSTEM` nor should it be checking `target_xxx`.

please review the manaul for more details:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Specifying-Target-Triplets.html

**Comment by rbowler** [comment]
As I don't know enough about autoconf to have an opinion on this, I will defer to Mike Frysinger (a.k.a. vapier) and close the issue.
