### ISSUE TITLE
Incorrect instruction trace operand data and "u" command disassembles incorrect virtual page

### ISSUE THREAD

**Issue by PeterCoghlan** [rbowler/spinhawk#39]
When tracing instructions or single stepping, incorrect instruction operand data can sometimes be displayed on the Hercules console.  The data is incorrect because it is from the wrong virtual page.  This is due to a stale page table entry being retrieved from a temporary translation lookaside buffer in translate_addr() due in turn to regs->tlbID being set to zero which appears to not be valid.  Before calling translate_addr(), a temporary copy is made of part of the regs structure by copy_regs() but tlbID is not copied (because it appears in the regs structure after regs_copy_end) and the temporary tlbID is not initialised.

The "u" command is similarly affected in that it can end up disassembling code from the wrong virtual  page.

The "v" command is not affected as it bypasses the temporary TLB.

Data used for actual instruction execution is not affected because regs->tlbID is never zero when this is being fetched.

S/370 mode and S/390 mode are both affected.  I have not tested in Z/Arch mode.

The bug is elusive and difficult to provoke.  It appears to only affects pages which have been remapped at least once.  Fixed pages in an operating system kernel for example are not affected.

One possible fix appears to be to use ARCH_DEP(purge_tlb) to clear the new temporary TLBs in copy_regs() instead of memset().  Another possible fix is to always bypass use of the temporary TLB for data displayed on the Hercules console in the same way the "v" command does by calling virt_to_abs(), display_virt() etc with ACCTYPE_LRA instead of ACCTYPE_READ or ACCTYPE_INSTFETCH.

Some further thought may be required about the involvement of TLBs in fetching data to be displayed on the Hercules console.

**Comment by rbowler** [comment]
Fix applied https://github.com/rbowler/spinhawk/commit/1e7cf4c7d77d32a05988c359b3d1f674fa1ca6b9
