### ISSUE TITLE
Cannot define a full 3350 emulated disk (somitcw)

### ISSUE THREAD

**Issue by rbowler** [rbowler/spinhawk#4]
C:\Trash>dasdinit -z test.3350 3350 test50 1026
HHCDU044I Creating 3350 volume TEST50: 1026 cyls, 30 trks/cyl, 19456 bytes/track
HHCDU028E device type 3350 not found in dasd table
HHCDI002I DASD initialization unsuccessful

**Comment by somitcw** [comment]
A 3350 has 555 data cylinders, 5 alternate cylinders, but also has hardware and CE cylinders starting at cylinder 1024.
An undocumented restriction number prevents defining a complete 3350.

**Comment by rbowler** [comment]
I don't think there was ever any intention to support hardware and CE cylinders in Hercules (certainly not on my part anyway). Paolo says that dasdinit doesn't let you define more than 560 cylinders on a 3350 which sounds entirely plausible as an explanation. What the message is probably trying to tell you is that it doesn't have a definition of a 3350 with the number of cylinders requested, although I agree it's hard to guess that from the message text. As the sands of time flow relentlessly on and the grim reaper appears on the horizon, I am going to dispose of this issue by closing it as "won't fix".

**Comment by somitcw** [comment]
Issue fixed years ago in Hercules 4.0
Unique cylinder limitation was removed in Hercules 4.0
Other than track overflow and alternate track use,
3350 emulation now matches both real disks and old Hercules emulation.
No reason to keep this issue open.
