### ISSUE TITLE
Issues with 3330 disks?

### ISSUE THREAD

**Issue by b4** [rbowler/spinhawk#5]
I've tried attaching a 3330 device containing an install of TSS to several instances both running and non-running, regardless of device number or current state the machine will eventually get stuck in a WAIT state and respond to nothing.

This has been reproduced on PowerPC (OS X) only.

http://gewt.net/tssres.250 is the offending disk.  Let me know if I'm just nuts or if I found a bug.

**Comment by rbowler** [comment]
Resurrecting TSS/360 sounds like an interesting project, however it is probably not immune to copyright claims so I don't want to risk looking at it. I'm afraid I don't have enough information to answer your last question, but let's assume a third possibility, it could be a corrupt disk image.
