### ISSUE TITLE
Why has Hercules turned into a Fish Fest ?

### ISSUE THREAD

**Issue by gordboy** [rbowler/spinhawk#51]
Can you please explain to me why a project that started off as a decent working Linux project has morphed into a broken Windows project.

There is no need whatever for a gui interface nor loadable modules. It seems to me that whole direction is merely to support a crappy Windows GUI that nobody asked for nor needs. Once you are working in the emulation so to speak, all there is is devices and terminals. And devices and terminals have no obvious need for any gui whatsover.

It is impossible to build the spinhawk Hercules without dynamic module support, and this is utterly ridiculous.

You can tell by looking at the hyperion fork that Hercules has become a joke. In order to support a crappy Windows telnet client, the console telnet code has become so broken that vanilla telnet clients do not work any longer.

Why have you allowed any of this mess to happen? And what are you going to do about it?

Obviously not every contribution in the New Era has been disastrous, but there have been enough to warrant a complete overhaul of the code and a return to sanity.

**Comment by jphartmann** [comment]
I would like to discuss the technical substance of this in private.  Would gordboy be kind enough to identify him/herself to jphartmann@gmail.com?  Thanks.

**Comment by g4ugm** [comment]
From what I remember, and I can't currently get into Yahoo to check old messages, Rogers original intent was to create portable, cross platform dependant code that ran on any platform. Having spent much time years writing such code I understand that it introduces complications, and may result in "lowest common denominator" code and perhaps its time to reconsider which platforms its developed for. Its worth remembering that there is no point in having a project if it has no users. Last time I checked there were more Windows users than Linux users. This may have changed but having a project with no users is pointless...

**Comment by jphartmann** [comment]
As I understand it, the original was Cygwin on Windows.  While Cygwin was great in the early 90s, nowadays with VMWARE nobody uses Cygwin (not least for its licence).  So the focus ought to change.

As for projects without users, it is equally pointless to have a project that has no developers.  

I wonder why this thread got to spinhawk; I should have thought it belongs in Hyperion, rather.

**Comment by g4ugm** [comment]
If its stable it doesn't need developers it needs bug fixers who are a different animal. I think the real problem with Hercules is that its now basically a mature project in maintenance mode. There isn't a lot to develop. There are bugs to fix but typically programmers don't like bug fixing. The things that would be good such as implementing the new features in "Z" are difficult to test on a traditional OS , given IBM's licencing stance. Even getting a supported copy of a recent zLinux can be challenging. Several of the releases specifically exclude Hercules as a supported platform.

**Comment by gordboy** [comment]
The reason it got brought up here is because this is supposedly where the senior developers hang out.

And I was very grateful for a partial return to sanity, but it seems you have allowed the buffoonery to continue. The latest 'fix' is to a 'fix' from the same person. Round and round in endless circles. Buffoonery heaped on buffoonery.

The actual problem here is that there is no overview. And allowing this stupidity to continue has only one possible outcome.

Allowing someone to make endless bogus commits, who has totally poisoned the codebase, is not acceptable in any project. Time you woke up.

Anyways, I am totally wasting my time. Most of the people who comment here and in the forums are pretty clueless. Passengers. Excess baggage. Surplus ballast. Choose your metaphor.

**Comment by Fish-Git** [comment]
> The reason it got brought up here is because this is supposedly where the senior developers hang out.

We team of senior developers usually hang out on [Hercules-390](https://github.com/hercules-390).

> Anyways, I am totally wasting my time. Most of the people who comment here and in the forums are pretty clueless. Passengers. Excess baggage. Surplus ballast. Choose your metaphor.

Why are you being so rude and insulting? I don't know what it was that I or others did to upset you so much, but I hereby sincerely apologize for whatever it was that I myself did. I still don't know what it was but I apologize for it anyway.

In the spirit of atonement I would also like to offer you the following two olive branches:

- https://groups.yahoo.com/neo/groups/hercules-390/conversations/messages/79947
- https://groups.yahoo.com/neo/groups/hercules-390/conversations/messages/79946

It is my hope that peace can be made.

Thank you and take care.
