### ISSUE TITLE
No configure script (only configure.AC, which doesn't work cleanly)

### ISSUE THREAD

**Issue by swhobbit** [rbowler/spinhawk#67]
The project has a `configure.AC` and `config.sh` script, but no `configure` script, and no instructions on how to successfully use `autoconf` to create one.  

### Environments

-  MacOS Sierra (10.12.6)
-  Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-87-generic x86_64)
### Steps to Reproduce

- Install `autoconf` via MacPorts (macOS) or `apt-get` (Ubuntu)
- Install Sierra `xcode` (MacOS).
- execute `autoconf`

## Expected Result

Working `configure` script is created which can configure a build of Hercules.

## Actual Result

Numerous undefined variable messages, and broken `configure` script is created.

**Comment by rbowler** [comment]
Drew - you have to first create the configure script by running autogen.sh. This is documented in the INSTALL file. However, I notice that the hercinst.html file lacks this important detail, and I will rectify that omission straightaway.

 I don't know enough about autoconf to know why it was done that way. The autoconf enablement for Hercules was done in 2001 by Matt Zimmerman, lately CTO of Ubuntu (yes, we were honoured to have him working on the project for a while). He might have the answer, but I guess he has more important things on his plate now.

**Comment by rbowler** [comment]
One further comment: if you unzip the source from the hercules-3.xx.tar.gz file then you should find that there is already a pregenerated configure script included. You only need to run autogen.sh if you cloned the source from the github repository. This is probably why it doesn't mention it in hercinst.html. But we cannot expect people to guess that, so I will add it to hercinst.html.

**Comment by rbowler** [comment]
Fixed by bc91626bd5b564ea819004707bdf57ff207192f1

**Comment by swhobbit** [comment]
There is little reason to make everyone building Hercules from GitHub have to run `autogen.sh` (which requires `automake` be installed); that should be only be required if the dependencies change (i.e. new libraries).  

This especially true since the usually references on the mailing lists for to the source are GitHub and not a pre-built tar.gz file.   (The latter being ~ two years old)
