### ISSUE TITLE
Request to add S37x to 3.13

### ISSUE THREAD

**Issue by laddiehanus** [rbowler/spinhawk#68]
I have my own customized MVS 3.8 system and thus TK4- is not a good fit for me. I am looking to make some mods to implement Dual address space and would like a stable (not regularly changing) hercules to do this work on. As I am currently unemployed due to layoffs I can work on this but it will take me a few months to relearn my way around the code. I also seem to remember that Jurgen has made some updates to his version of hercules.

**Comment by rbowler** [comment]
Laddie - It is not planned to activate the 37x instructions as standard in 3.13, but you can always do so by uncommenting the desired features in feat370.h and recompiling. However, if Dual Address Space is what you want, then this is already included in the base set of S/370 features in spinhawk.
