### ISSUE TITLE
commadpt.c: BSC mode. Should stop writing after ETX/ETB

### ISSUE THREAD

**Issue by MattisLind** [rbowler/spinhawk#94]
The IBM 2703 Transmission Control Component Description document specifies on
page 58 that a channel write shall stop if an ETX or ETB control character
is detected in the data stream.

It is also mentioned on page 48 in the same document that bytes following the ETX or ETB shall
not be transferred to the line if they are received from the channel.

This fix detects the presence of these characters and breaks out of the loop
if these occur in the data stream.

I have made a PR for this:
[https://github.com/rbowler/spinhawk/pull/93](https://github.com/rbowler/spinhawk/pull/93)

**Comment by rbowler** [comment]
Merged manually by 515e33f7aa027f71ce42c1bafea14bcf60e84290

**Comment by rbowler** [comment]
Merged manually by 515e33f7aa027f71ce42c1bafea14bcf60e84290
